version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: 'no'
    volumes:
      - mariadb-data:/var/lib/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: core
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mariadb
      ADMINER_DEFAULT_DB_SERVER: mariadb
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DEFAULT_DB_NAME: core
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter tinymce
    expose:
      - 8081
    depends_on:
      - mariadb

  mq-service:
    container_name: mq-service
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'test'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - api-data:/var/lib/api
    depends_on:
      - mq-service
      - mariadb
    environment:
      NODE_ENV: 'development'
      APP_PORT: 3000
      TYPEORM_HOST: mariadb
      REDIS_HOST: redis
      AMQP_HOST: mq-service
      AMQP_USERNAME: test
      AMQP_PASSWORD: password
      TYPEORM_USERNAME: guest
      TYPEORM_PASSWORD: guest
      TYPEORM_DATABASE: core
      REDIS_PASSWORD: sOmE_sEcUrE_pAsS
      

  redis:
    image: 'redis:alpine'
    container_name: redis-cache
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master      

volumes:
  mariadb-data:
    driver: local
  rabbitmq-data:
    driver: local
  api-data:
    driver: local
  redis-data:
    driver: local
  redis.conf:
    driver: local
