name: Nestjs-Template-CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check docker-compose
        run: docker -v && docker-compose -v

      - name: Up Docker-Compose containers
        run: docker-compose up -d --build

      - name: Run e2e
        run: yarn && yarn test:e2e

      - name: Down Docker-Compose containers
        run: docker-compose down
